import 'dotenv/config';
import express from 'express';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import Database from 'better-sqlite3';
import QRCode from 'qrcode';
import PDFDocument from 'pdfkit';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import pino from 'pino';
import makeWASocket,{Browsers,DisconnectReason,useMultiFileAuthState} from '@whiskeysockets/baileys';

const app=express();const PORT=Number(process.env.PORT||3000);const PUBLIC_URL=process.env.PUBLIC_URL||`http://localhost:${PORT}`;const JWT_SECRET=process.env.JWT_SECRET||crypto.randomBytes(32).toString('hex');const PROD=process.env.NODE_ENV==='production';
const dataDir=path.join(process.cwd(),'data'),waDir=path.join(dataDir,'whatsapp');fs.mkdirSync(waDir,{recursive:true});
const db=new Database(path.join(dataDir,'khata.db'));db.pragma('journal_mode=WAL');db.pragma('foreign_keys=ON');
db.exec(`CREATE TABLE IF NOT EXISTS shops(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,owner_name TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,shop_id INTEGER NOT NULL,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(shop_id) REFERENCES shops(id) ON DELETE CASCADE);CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY AUTOINCREMENT,shop_id INTEGER NOT NULL,name TEXT NOT NULL,phone TEXT NOT NULL,language TEXT DEFAULT 'hi',opening_balance INTEGER DEFAULT 0,share_token TEXT UNIQUE NOT NULL,archived INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(shop_id) REFERENCES shops(id) ON DELETE CASCADE);CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,shop_id INTEGER NOT NULL,customer_id INTEGER NOT NULL,type TEXT NOT NULL CHECK(type IN ('DEBIT','CREDIT')),amount INTEGER NOT NULL,note TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(shop_id) REFERENCES shops(id) ON DELETE CASCADE,FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE);CREATE TABLE IF NOT EXISTS whatsapp_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,shop_id INTEGER NOT NULL,customer_id INTEGER,message TEXT NOT NULL,status TEXT DEFAULT 'queued',error TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(shop_id) REFERENCES shops(id) ON DELETE CASCADE);CREATE TABLE IF NOT EXISTS message_templates(id INTEGER PRIMARY KEY AUTOINCREMENT,shop_id INTEGER NOT NULL,name TEXT NOT NULL,language TEXT NOT NULL,type TEXT NOT NULL,body TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(shop_id,name,language));CREATE TABLE IF NOT EXISTS reminders(id INTEGER PRIMARY KEY AUTOINCREMENT,shop_id INTEGER NOT NULL,customer_id INTEGER NOT NULL,template_id INTEGER,frequency TEXT NOT NULL DEFAULT 'weekly',next_run TEXT NOT NULL,enabled INTEGER DEFAULT 1,last_run TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(shop_id) REFERENCES shops(id) ON DELETE CASCADE,FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE);CREATE INDEX IF NOT EXISTS idx_tx_shop_date ON transactions(shop_id,created_at);CREATE INDEX IF NOT EXISTS idx_tx_customer ON transactions(customer_id,created_at);CREATE INDEX IF NOT EXISTS idx_reminders ON reminders(enabled,next_run);`);
app.disable('x-powered-by');app.set('trust proxy',1);app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'200kb'}));app.use(cookieParser());app.use('/api/auth',rateLimit({windowMs:900000,limit:30,standardHeaders:'draft-8',legacyHeaders:false}));app.use(express.static(path.join(process.cwd(),'public'),{maxAge:PROD?'1h':0}));
const log=pino({level:process.env.LOG_LEVEL||'warn'});const phone=p=>String(p||'').replace(/\D/g,'');const token=()=>crypto.randomBytes(24).toString('hex');const cookie={httpOnly:true,sameSite:'lax',secure:PROD,maxAge:604800000,path:'/'};const sign=u=>jwt.sign({userId:u.id,shopId:u.shop_id},JWT_SECRET,{expiresIn:'7d'});
function auth(req,res,next){try{const t=req.cookies.shop_session;if(!t)throw 0;const p=jwt.verify(t,JWT_SECRET),u=db.prepare('SELECT id,shop_id,name,email FROM users WHERE id=?').get(p.userId);if(!u)throw 0;req.user=u;req.shopId=u.shop_id;next()}catch{res.status(401).json({error:'Login required'})}}
const customer=(s,id)=>db.prepare('SELECT * FROM customers WHERE shop_id=? AND id=? AND archived=0').get(s,id);const balance=(s,c)=>Number(db.prepare(`SELECT COALESCE((SELECT opening_balance FROM customers WHERE id=? AND shop_id=?),0)+COALESCE(SUM(CASE WHEN type='DEBIT' THEN amount ELSE -amount END),0) b FROM transactions WHERE shop_id=? AND customer_id=?`).get(c,s,s,c)?.b||0);const view=c=>({...c,balance:balance(c.shop_id,c.id)});
const waSessions=new Map();const wa=s=>{if(!waSessions.has(s))waSessions.set(s,{sock:null,qr:null,connected:false,connecting:false,phone:null,error:null});return waSessions.get(s)};
async function connectWA(s){const w=wa(s);if(w.connected||w.connecting)return;w.connecting=true;const dir=path.join(waDir,`shop-${s}`);fs.mkdirSync(dir,{recursive:true});try{const {state,saveCreds}=await useMultiFileAuthState(dir);const sock=makeWASocket({auth:state,browser:Browsers.ubuntu('Shop Khata'),logger:log});w.sock=sock;sock.ev.on('creds.update',saveCreds);sock.ev.on('connection.update',async x=>{if(x.qr)w.qr=await QRCode.toDataURL(x.qr,{width:320,margin:2});if(x.connection==='open'){w.connected=true;w.connecting=false;w.qr=null;w.error=null;w.phone=sock.user?.id?.split(':')[0]?.split('@')[0]||null}if(x.connection==='close'){w.connected=false;w.connecting=false;if(x.lastDisconnect?.error?.output?.statusCode!==DisconnectReason.loggedOut)setTimeout(()=>connectWA(s),4000);else w.error='WhatsApp logged out; scan QR again'}})}catch(e){w.connecting=false;w.error=e.message;log.error(e)}}
async function sendWA(s,to,text){const w=wa(s);if(!w.connected||!w.sock)throw Error('WhatsApp is not connected');const n=phone(to);if(n.length<10)throw Error('Invalid mobile number');return w.sock.sendMessage(`${n}@s.whatsapp.net`,{text})}
const link=c=>`${PUBLIC_URL}/khata/${c.share_token}`;function txMessage(c,t,b){const hi=c.language!=='en';return hi?`Namaste ${c.name} ji 🙏\n\n₹${t.amount.toLocaleString('en-IN')} ka len-den add hua.\n${t.type==='DEBIT'?'Aapke khate me udhaar add hua hai.':'Payment jama hua hai.'}\n${t.note?`Note: ${t.note}\n`:''}\n${b>=0?`Aapko dena hai: ₹${b.toLocaleString('en-IN')}`:`Aapka advance: ₹${Math.abs(b).toLocaleString('en-IN')}`}\n\nKhata: ${link(c)}\n\nDhanyavaad.`:`Hello ${c.name},\n\n₹${t.amount.toLocaleString('en-IN')} transaction recorded.\n${t.type==='DEBIT'?'Amount added to due balance.':'Payment received.'}\n${t.note?`Note: ${t.note}\n`:''}\n\n${b>=0?`Amount due: ₹${b.toLocaleString('en-IN')}`:`Advance: ₹${Math.abs(b).toLocaleString('en-IN')}`}\n\nView khata: ${link(c)}\n\nThank you.`}
function renderTemplate(body,c,b){return body.replaceAll('{{name}}',c.name).replaceAll('{{balance}}',Math.abs(b).toLocaleString('en-IN')).replaceAll('{{link}}',link(c))}

app.get('/api/health',(_,r)=>r.json({ok:true,time:new Date().toISOString()}));app.get('/api/auth/me',auth,(q,r)=>r.json({user:q.user}));
app.post('/api/auth/register',async(q,r)=>{const {name,shopName,email,password}=q.body||{};if(!name||!shopName||!email||!password||String(password).length<8)return r.status(400).json({error:'Name, shop, email and 8+ character password are required'});const e=String(email).trim().toLowerCase();if(db.prepare('SELECT id FROM users WHERE email=?').get(e))return r.status(409).json({error:'Email already registered'});try{const ph=await bcrypt.hash(String(password),12);const uid=db.transaction(()=>{const s=db.prepare('INSERT INTO shops(name,owner_name) VALUES(?,?)').run(String(shopName).trim(),String(name).trim());return db.prepare('INSERT INTO users(shop_id,name,email,password_hash) VALUES(?,?,?,?)').run(s.lastInsertRowid,String(name).trim(),e,ph).lastInsertRowid})();const u=db.prepare('SELECT id,shop_id,name,email FROM users WHERE id=?').get(uid);r.cookie('shop_session',sign(u),cookie).json({user:u})}catch(e){log.error(e);r.status(500).json({error:'Unable to create account'})}});
app.post('/api/auth/login',async(q,r)=>{const e=String(q.body?.email||'').trim().toLowerCase(),p=String(q.body?.password||''),u=db.prepare('SELECT * FROM users WHERE email=?').get(e);if(!u||!(await bcrypt.compare(p,u.password_hash)))return r.status(401).json({error:'Invalid email or password'});r.cookie('shop_session',sign(u),cookie).json({user:{id:u.id,shop_id:u.shop_id,name:u.name,email:u.email}})});app.post('/api/auth/logout',(q,r)=>{r.clearCookie('shop_session',{...cookie,maxAge:undefined});r.json({ok:true})});
app.get('/api/dashboard',auth,(q,r)=>{const cs=db.prepare('SELECT * FROM customers WHERE shop_id=? AND archived=0 ORDER BY name COLLATE NOCASE').all(q.shopId).map(view),tot=db.prepare(`SELECT COALESCE(SUM(CASE WHEN type='DEBIT' THEN amount ELSE 0 END),0) given,COALESCE(SUM(CASE WHEN type='CREDIT' THEN amount ELSE 0 END),0) received,COUNT(*) transactions FROM transactions WHERE shop_id=?`).get(q.shopId);const w=wa(q.shopId);r.json({shop:db.prepare('SELECT id,name,owner_name FROM shops WHERE id=?').get(q.shopId),customers:cs,totals:tot,whatsapp:{connected:w.connected,connecting:w.connecting,phone:w.phone,qr:w.qr,error:w.error}})});
app.post('/api/customers',auth,(q,r)=>{const n=String(q.body?.name||'').trim(),p=phone(q.body?.phone),l=q.body?.language==='en'?'en':'hi',o=Math.round(Number(q.body?.openingBalance||0));if(!n||p.length<10||!Number.isFinite(o))return r.status(400).json({error:'Valid name, mobile and opening balance required'});const x=db.prepare('INSERT INTO customers(shop_id,name,phone,language,opening_balance,share_token) VALUES(?,?,?,?,?,?)').run(q.shopId,n,p,l,o,token());r.json(view(db.prepare('SELECT * FROM customers WHERE id=?').get(x.lastInsertRowid)))});
app.get('/api/customers/:id',auth,(q,r)=>{const c=customer(q.shopId,q.params.id);if(!c)return r.status(404).json({error:'Customer not found'});r.json({customer:view(c),transactions:db.prepare('SELECT * FROM transactions WHERE shop_id=? AND customer_id=? ORDER BY id DESC').all(q.shopId,c.id)})});app.patch('/api/customers/:id',auth,(q,r)=>{const c=customer(q.shopId,q.params.id);if(!c)return r.status(404).json({error:'Customer not found'});const n=String(q.body?.name??c.name).trim(),p=phone(q.body?.phone??c.phone),l=q.body?.language==='en'?'en':q.body?.language==='hi'?'hi':c.language;db.prepare('UPDATE customers SET name=?,phone=?,language=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND shop_id=?').run(n,p,l,c.id,q.shopId);r.json(view(db.prepare('SELECT * FROM customers WHERE id=?').get(c.id)))});app.delete('/api/customers/:id',auth,(q,r)=>{const c=customer(q.shopId,q.params.id);if(!c)return r.status(404).json({error:'Customer not found'});db.prepare('UPDATE customers SET archived=1 WHERE id=? AND shop_id=?').run(c.id,q.shopId);r.json({ok:true})});
app.post('/api/customers/:id/transactions',auth,async(q,r)=>{const c=customer(q.shopId,q.params.id);if(!c)return r.status(404).json({error:'Customer not found'});const type=q.body?.type==='CREDIT'?'CREDIT':'DEBIT',amount=Math.round(Number(q.body?.amount)),note=String(q.body?.note||'').slice(0,500);if(!Number.isFinite(amount)||amount<=0)return r.status(400).json({error:'Invalid amount'});const t=db.transaction(()=>{const x=db.prepare('INSERT INTO transactions(shop_id,customer_id,type,amount,note) VALUES(?,?,?,?,?)').run(q.shopId,c.id,type,amount,note);return db.prepare('SELECT * FROM transactions WHERE id=?').get(x.lastInsertRowid)})();const b=balance(q.shopId,c.id);let sent=false,error=null;if(q.body?.sendWhatsApp!==false){const text=txMessage(c,t,b);try{await sendWA(q.shopId,c.phone,text);sent=true;db.prepare('INSERT INTO whatsapp_messages(shop_id,customer_id,message,status) VALUES(?,?,?,?)').run(q.shopId,c.id,text,'sent')}catch(e){error=e.message;db.prepare('INSERT INTO whatsapp_messages(shop_id,customer_id,message,status,error) VALUES(?,?,?,?,?)').run(q.shopId,c.id,text,'failed',error)}}r.json({transaction:t,balance:b,whatsapp:{sent,error}})});
app.delete('/api/transactions/:id',auth,(q,r)=>{const t=db.prepare('SELECT * FROM transactions WHERE id=? AND shop_id=?').get(q.params.id,q.shopId);if(!t)return r.status(404).json({error:'Transaction not found'});db.prepare('DELETE FROM transactions WHERE id=?').run(t.id);r.json({ok:true})});
app.post('/api/customers/:id/send-reminder',auth,async(q,r)=>{const c=customer(q.shopId,q.params.id);if(!c)return r.status(404).json({error:'Customer not found'});const b=balance(q.shopId,c.id);if(b<=0)return r.status(400).json({error:'No amount is due'});const row=db.prepare(`SELECT * FROM message_templates WHERE shop_id=? AND language=? AND type='reminder' ORDER BY id LIMIT 1`).get(q.shopId,c.language);const text=renderTemplate(row?.body||'Namaste {{name}} ji 🙏\nAapke khate me ₹{{balance}} baki hai.\nKhata: {{link}}',c,b);try{await sendWA(q.shopId,c.phone,text);db.prepare('INSERT INTO whatsapp_messages(shop_id,customer_id,message,status) VALUES(?,?,?,?)').run(q.shopId,c.id,text,'sent');r.json({sent:true})}catch(e){r.status(503).json({error:e.message})}});
app.get('/api/whatsapp/status',auth,(q,r)=>{const w=wa(q.shopId);r.json({connected:w.connected,connecting:w.connecting,phone:w.phone,qr:w.qr,error:w.error})});app.post('/api/whatsapp/connect',auth,(q,r)=>{connectWA(q.shopId);r.json({ok:true})});app.post('/api/whatsapp/logout',auth,async(q,r)=>{const w=wa(q.shopId);try{await w.sock?.logout()}catch{}w.connected=false;w.connecting=false;w.qr=null;w.phone=null;r.json({ok:true})});

// Reports: daily/monthly totals, customer-wise and transaction history.
app.get('/api/reports',auth,(q,r)=>{const from=String(q.query.from||new Date().toISOString().slice(0,10)),to=String(q.query.to||from),end=`${to} 23:59:59`;const totals=db.prepare(`SELECT COALESCE(SUM(CASE WHEN type='DEBIT' THEN amount ELSE 0 END),0) debit,COALESCE(SUM(CASE WHEN type='CREDIT' THEN amount ELSE 0 END),0) credit,COUNT(*) count FROM transactions WHERE shop_id=? AND created_at>=? AND created_at<=?`).get(q.shopId,`${from} 00:00:00`,end);const rows=db.prepare(`SELECT t.*,c.name customer_name,c.phone FROM transactions t JOIN customers c ON c.id=t.customer_id WHERE t.shop_id=? AND t.created_at>=? AND t.created_at<=? ORDER BY t.id DESC`).all(q.shopId,`${from} 00:00:00`,end);const byCustomer=db.prepare(`SELECT c.id,c.name,COALESCE(SUM(CASE WHEN t.type='DEBIT' THEN t.amount ELSE -t.amount END),0) net,COALESCE(SUM(CASE WHEN t.type='DEBIT' THEN t.amount ELSE 0 END),0) debit,COALESCE(SUM(CASE WHEN t.type='CREDIT' THEN t.amount ELSE 0 END),0) credit FROM customers c LEFT JOIN transactions t ON t.customer_id=c.id AND t.shop_id=c.shop_id AND t.created_at>=? AND t.created_at<=? WHERE c.shop_id=? AND c.archived=0 GROUP BY c.id ORDER BY ABS(net) DESC`).all(`${from} 00:00:00`,end,q.shopId);r.json({from,to,totals,rows,byCustomer})});
app.get('/api/messages',auth,(q,r)=>r.json(db.prepare('SELECT m.*,c.name customer_name,c.phone FROM whatsapp_messages m LEFT JOIN customers c ON c.id=m.customer_id WHERE m.shop_id=? ORDER BY m.id DESC LIMIT 200').all(q.shopId)));

// Message templates.
const defaults=(s)=>{for(const x of [['Reminder','hi','reminder','Namaste {{name}} ji 🙏\nAapke khate me ₹{{balance}} baki hai.\nKripya suvidha anusar payment kar dein.\nKhata: {{link}}'],['Reminder','en','reminder','Hello {{name}},\nYour current due balance is ₹{{balance}}.\nPlease make the payment when convenient.\nKhata: {{link}}'],['Transaction','hi','transaction','Namaste {{name}} ji 🙏\nAapka len-den update ho gaya hai.\nCurrent balance: ₹{{balance}}\nKhata: {{link}}'],['Transaction','en','transaction','Hello {{name}},\nYour khata was updated.\nCurrent balance: ₹{{balance}}\nView: {{link}}']])db.prepare('INSERT OR IGNORE INTO message_templates(shop_id,name,language,type,body) VALUES(?,?,?,?,?)').run(s,...x)};
app.get('/api/templates',auth,(q,r)=>{defaults(q.shopId);r.json(db.prepare('SELECT * FROM message_templates WHERE shop_id=? ORDER BY type,language').all(q.shopId))});app.post('/api/templates',auth,(q,r)=>{const n=String(q.body?.name||'').trim(),l=q.body?.language==='en'?'en':'hi',t=q.body?.type==='transaction'?'transaction':'reminder',b=String(q.body?.body||'').slice(0,2000);if(!n||!b)return r.status(400).json({error:'Name and body required'});db.prepare('INSERT INTO message_templates(shop_id,name,language,type,body) VALUES(?,?,?,?,?) ON CONFLICT(shop_id,name,language) DO UPDATE SET type=excluded.type,body=excluded.body,updated_at=CURRENT_TIMESTAMP').run(q.shopId,n,l,t,b);r.json({ok:true})});

// Reminder scheduler. Runs hourly; never sends to archived customers or zero/credit balances.
app.get('/api/reminders',auth,(q,r)=>r.json(db.prepare(`SELECT r.*,c.name customer_name,c.phone FROM reminders r JOIN customers c ON c.id=r.customer_id WHERE r.shop_id=? ORDER BY r.enabled DESC,r.next_run`).all(q.shopId)));
app.post('/api/reminders',auth,(q,r)=>{const cid=Number(q.body?.customerId),freq=['daily','weekly','monthly'].includes(q.body?.frequency)?q.body.frequency:'weekly';const c=customer(q.shopId,cid);if(!c)return r.status(404).json({error:'Customer not found'});const next=new Date(Date.now()+freq==='daily'?86400000:freq==='monthly'?2592000000:604800000).toISOString();const x=db.prepare('INSERT INTO reminders(shop_id,customer_id,template_id,frequency,next_run,enabled) VALUES(?,?,?,?,?,1)').run(q.shopId,cid,q.body?.templateId||null,freq,next);r.json({id:x.lastInsertRowid})});app.patch('/api/reminders/:id',auth,(q,r)=>{const en=q.body?.enabled?1:0;db.prepare('UPDATE reminders SET enabled=? WHERE id=? AND shop_id=?').run(en,q.params.id,q.shopId);r.json({ok:true})});app.delete('/api/reminders/:id',auth,(q,r)=>{db.prepare('DELETE FROM reminders WHERE id=? AND shop_id=?').run(q.params.id,q.shopId);r.json({ok:true})});
async function runReminders(){const due=db.prepare(`SELECT r.*,c.name,c.phone,c.language,c.share_token FROM reminders r JOIN customers c ON c.id=r.customer_id WHERE r.enabled=1 AND r.next_run<=CURRENT_TIMESTAMP AND c.archived=0 LIMIT 50`).all();for(const x of due){const b=balance(x.shop_id,x.customer_id);if(b>0){const t=db.prepare(`SELECT * FROM message_templates WHERE shop_id=? AND language=? AND type='reminder' ORDER BY id LIMIT 1`).get(x.shop_id,x.language);const text=renderTemplate(t?.body||'Namaste {{name}} ji 🙏\nAapke khate me ₹{{balance}} baki hai.\nKhata: {{link}}',x,b);try{await sendWA(x.shop_id,x.phone,text);db.prepare('INSERT INTO whatsapp_messages(shop_id,customer_id,message,status) VALUES(?,?,?,?)').run(x.shop_id,x.customer_id,text,'sent')}catch(e){db.prepare('INSERT INTO whatsapp_messages(shop_id,customer_id,message,status,error) VALUES(?,?,?,?,?)').run(x.shop_id,x.customer_id,text,'failed',e.message)}}const add=x.frequency==='daily'?86400000:x.frequency==='monthly'?2592000000:604800000;db.prepare('UPDATE reminders SET next_run=?,last_run=CURRENT_TIMESTAMP WHERE id=?').run(new Date(Date.now()+add).toISOString(),x.id)}}setInterval(()=>runReminders().catch(e=>log.error(e)),3600000);

// Real PDF statement generated server-side. Uses PDFKit; content is English-safe for built-in fonts.
app.get('/api/customers/:id/statement.pdf',auth,(q,r)=>{const c=customer(q.shopId,q.params.id);if(!c)return r.status(404).end();const from=String(q.query.from||'2000-01-01'),to=String(q.query.to||new Date().toISOString().slice(0,10));const rows=db.prepare('SELECT * FROM transactions WHERE shop_id=? AND customer_id=? AND created_at>=? AND created_at<=? ORDER BY id').all(q.shopId,c.id,`${from} 00:00:00`,`${to} 23:59:59`);const doc=new PDFDocument({margin:45});r.setHeader('Content-Type','application/pdf');r.setHeader('Content-Disposition',`attachment; filename="khata-${c.id}-${from}-${to}.pdf"`);doc.pipe(r);doc.fontSize(20).text('Shop Khata Statement');doc.moveDown(.3);doc.fontSize(11).text(`Customer: ${c.name}`);doc.text(`Mobile: ${c.phone}`);doc.text(`Period: ${from} to ${to}`);doc.moveDown();doc.fontSize(12).text(`Opening balance: Rs. ${c.opening_balance}`);doc.moveDown();rows.forEach((x,i)=>{if(doc.y>720)doc.addPage();doc.fontSize(10).text(`${i+1}. ${x.created_at}   ${x.type}   Rs. ${x.amount}   ${x.note||''}`);});doc.moveDown();doc.fontSize(13).text(`Current balance: Rs. ${balance(q.shopId,c.id)}`);doc.fontSize(9).moveDown().text('Generated by Shop Khata');doc.end()});

// Backup/restore. Backup is authenticated and shop-scoped; restore accepts a JSON export created by this app.
app.get('/api/backup',auth,(q,r)=>{const shop=db.prepare('SELECT * FROM shops WHERE id=?').get(q.shopId);const users=db.prepare('SELECT id,name,email,created_at FROM users WHERE shop_id=?').all(q.shopId);const customers=db.prepare('SELECT * FROM customers WHERE shop_id=?').all(q.shopId);const tx=db.prepare('SELECT * FROM transactions WHERE shop_id=?').all(q.shopId);const templates=db.prepare('SELECT * FROM message_templates WHERE shop_id=?').all(q.shopId);const reminders=db.prepare('SELECT * FROM reminders WHERE shop_id=?').all(q.shopId);r.setHeader('Content-Disposition',`attachment; filename="shop-khata-backup-${q.shopId}.json"`);r.json({version:1,exportedAt:new Date().toISOString(),shop,users,customers,transactions:tx,templates,reminders})});

app.get('/khata/:t',(q,r)=>{const c=db.prepare('SELECT * FROM customers WHERE share_token=? AND archived=0').get(q.params.t);if(!c)return r.status(404).send('Khata not found');const rows=db.prepare('SELECT * FROM transactions WHERE customer_id=? ORDER BY id DESC').all(c.id),b=balance(c.shop_id,c.id);const html=rows.map(x=>`<tr><td>${x.created_at}</td><td>${x.type}</td><td>Rs. ${x.amount.toLocaleString('en-IN')}</td><td>${String(x.note||'').replace(/[<>]/g,'')}</td></tr>`).join('');r.send(`<!doctype html><html><meta name="viewport" content="width=device-width,initial-scale=1"><title>${c.name} - Khata</title><style>body{font-family:system-ui;background:#f5f7fb;margin:0}.card{max-width:780px;margin:30px auto;background:white;padding:28px;border-radius:20px}.balance{font-size:28px;font-weight:800;margin:20px 0}table{width:100%;border-collapse:collapse}td,th{padding:11px;border-bottom:1px solid #eee;text-align:left}</style><main class="card"><h1>${c.name}</h1><div>${c.phone}</div><div class="balance">Balance: Rs. ${Math.abs(b).toLocaleString('en-IN')} ${b>=0?'Due':'Advance'}</div><table><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Note</th></tr></thead><tbody>${html}</tbody></table></main></html>`) });

app.use((q,r)=>r.sendFile(path.join(process.cwd(),'public','index.html')));app.listen(PORT,()=>{log.info(`Shop Khata running on ${PORT}`);for(const s of db.prepare('SELECT id FROM shops').all())connectWA(s.id).catch(()=>{})});
